### ISSUE TITLE
java.lang.NoSuchMethodError: No static method deleteInjectedLoggable

### ISSUE THREAD

**Issue by nAkhmedov** [ddssingsong/webrtc_android#39]
Thank you for the great lib, app is crashed and here stacktrace, Could you help me, what is the reason?

```    java.lang.NoSuchMethodError: No static method deleteInjectedLoggable()V in class Lorg/webrtc/Logging; or its super classes (declaration of 'org.webrtc.Logging' appears in /data/app/~~QKsMfJBKf6cpivZeQVpczA==/com.packagename-2OIgEp71kemnbY6gmlnn_Q==/base.apk!classes3.dex)
        at org.webrtc.PeerConnectionFactory.initialize(PeerConnectionFactory.java:291)
        at com.packagename.meeting.PeerConnectionHelper.createConnectionFactory(PeerConnectionHelper.java:221)
        at com.packagename.meeting.PeerConnectionHelper.lambda$onJoinToRoom$0$PeerConnectionHelper(PeerConnectionHelper.java:140)
        at com.packagename.meeting.-$$Lambda$PeerConnectionHelper$shvUap96rkuUOOTcV81kaXKQuAw.run(Unknown Source:6)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)```

**Comment by ddssingsong** [comment]
已修复
