### ISSUE TITLE
Encounter SIGABRT 6 error in Caller inside function drainCandidate()

### ISSUE THREAD

**Issue by ngtrphuong** [ddssingsong/webrtc_android#49]
Hi,

This issue happens frequently on both of self-compiled lib or official lib,

`
D/dds_test: addRemoteIceCandidate  2222
W/libEGL: EGLNativeWindowType 0xc6f39808 disconnect failed
W/System.err:     at java.util.ArrayList$Itr.next(ArrayList.java:860)
        at com.dds.skywebrtc.engine.webrtc.Peer.drainCandidates(Peer.java:298)
        at com.dds.skywebrtc.engine.webrtc.Peer.onSetSuccess(Peer.java:260)
D/dds_test: receiveIceCandidate--Note5
E/rtc: #
    # Fatal error in: gen/sdk/android/generated_metrics_jni/../../../../../../../../usr/local/google/home/sakal/code/webrtc-aar-release/src/sdk/android/src/jni/jni_generator_helper.h, line 94
    # last system error: 0
    # Check failed: !env->ExceptionCheck()
    # 
D/dds_test: addRemoteIceCandidate
D/dds_test: addRemoteIceCandidate  2222
D/SurfaceView: destroy() Surface(name=SurfaceView - com.dds.webrtc.debug/com.dds.core.voip.CallSingleActivity@a6429e@0[13507])/@0x34ab17f org.webrtc.SurfaceViewRenderer{a6429e V.E...... ........ 0,0-1440,2792}
D/dds_test: receiveIceCandidate--Note5
A/libc: Fatal signal 6 (SIGABRT), code -6 (SI_TKILL) in tid 15343 (signaling_threa), pid 13507 (ds.webrtc.debug)
D/dds_test: addRemoteIceCandidate
    addRemoteIceCandidate  2222
`

Or 

`
E/stun_port.cc: (line 284): Port[556c6c00:audio:1:0:local:Net[lo:127.0.0.0/8:Loopback:id=1]]: UDP send of 96 bytes failed with error 22
W/port.cc: (line 1246): Conn[23fed000:audio:Net[lo:127.0.0.0/8:Loopback:id=1]:7QYlvr0f:1:0:local:udp:127.0.0.1:47610->uu7x8KeF:1:2122260223:local:udp:192.168.28.135:47115|C--W|-|0|0|9114193830701055486|-]: Failed to send STUN ping  err=-1 id=2b596b4b37527533782f6976
I/port.cc: (line 1756): Conn[23fed000:audio:Net[lo:127.0.0.0/8:Loopback:id=1]:7QYlvr0f:1:0:local:udp:127.0.0.1:47610->uu7x8KeF:1:2122260223:local:udp:192.168.28.135:47115|C--W|-|0|0|9114193830701055486|-]: Sent STUN ping, id=2b596b4b37527533782f6976, use_candidate=0, nomination=0
W/System.err: java.util.ConcurrentModificationException
W/libEGL: EGLNativeWindowType 0x702b695010 disconnect failed
D/SurfaceView: destroy() Surface(name=SurfaceView - com.dds.webrtc.debug/com.dds.core.voip.CallSingleActivity@e1f20cc@0[20124])/@0x9074f15 org.webrtc.SurfaceViewRenderer{e1f20cc V.E...... ........ 0,0-1440,2960}
D/SurfaceView: onWindowVisibilityChanged(0) true org.webrtc.SurfaceViewRenderer{e1f20cc V.E...... ......I. 0,0-1440,2960} of ViewRootImpl@ca09235[CallSingleActivity]
W/System.err:     at java.util.ArrayList$Itr.next(ArrayList.java:860)
        at com.dds.skywebrtc.engine.webrtc.Peer.drainCandidates(Peer.java:298)
        at com.dds.skywebrtc.engine.webrtc.Peer.onSetSuccess(Peer.java:260)
E/rtc: #
    # Fatal error in: gen/sdk/android/generated_base_jni/jni/../../../../../../../sdk/android/src/jni/jni_generator_helper.h, line 85
    # last system error: 0
    # Check failed: !env->ExceptionCheck()
    # 
A/libc: Fatal signal 6 (SIGABRT), code -6 (SI_TKILL) in tid 21306 (signaling_threa), pid 20124 (ds.webrtc.debug)
E/ds.webrtc.debu: No package ID ff found for ID 0xffffffff.
I/org.webrtc.Logging: EglRenderer: Initializing EglRenderer
`

Further info of this can be seen in enclosed log,

[SIGARBT6 Error from Caller in drainCandidate function.log](https://github.com/ddssingsong/webrtc_android/files/6167695/SIGARBT6.Error.from.Caller.in.drainCandidate.function.log)

**Comment by ngtrphuong** [comment]
Never mind! This issue is fixed in your new codes,
Many thanks,
